### ISSUE TITLE
Autosub install - HTTPError: (404, 'Missing parameters: skipstringen,skipstringnl')

### ISSUE THREAD

**Issue by ajongsma** [ajongsma/OSX_MediaCenter#2]
Error while saving in configuration screen:
Traceback (most recent call last):
  File "/Autosub/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/Autosub/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Autosub/cherrypy/_cpdispatch.py", line 67, in __call__
    raise sys.exc_info()[1]
HTTPError: (404, 'Missing parameters: skipstringen,skipstringnl')

-----
#Known error

Status: Awaiting fix from Autosub
https://github.com/BenjV/autosub/issues/2

**Comment by ajongsma** [comment]
Error doesn't appear on https://github.com/clone1612/autosub-bootstrapbill
